

export default defaultTables = { claszs : `CREATE TABLE IF NOT EXISTS claszs (
id INTEGER NOT NULL,
schoolid INTEGER NOT NULL,
typeid INTEGER NOT NULL,
name TEXT NOT NULL,
abbrv TEXT NOT NULL,
is_active tinyINTEGER NOT NULL,
is_delete tinyINTEGER NOT NULL,
PRIMARY KEY (id)`,
claszunits : `CREATE TABLE IF NOT EXISTS claszunits (
id INTEGER NOT NULL,
claszid INTEGER NOT NULL,
name TEXT NOT NULL,
abbrv TEXT NOT NULL,
is_active tinyINTEGER NOT NULL,
is_delete tinyINTEGER NOT NULL,
PRIMARY KEY (id)
)`,
schools : `CREATE TABLE IF NOT EXISTS schools (
id bigINTEGER NOT NULL ,
name TEXT NOT NULL,
schoolcode TEXT NOT NULL,
abbrv TEXT NOT NULL,
typeid INTEGER NOT NULL,
phone1 TEXT NOT NULL,
phone2 TEXT NOT NULL,
color TEXT NOT NULL,
links TEXT NOT NULL,
signatory INTEGER NOT NULL,
office INTEGER NOT NULL,
email TEXT NOT NULL,
country TEXT NOT NULL,
states TEXT NOT NULL,
address text NOT NULL,
signed TEXT NOT NULL,
is_active tinyINTEGER NOT NULL,
is_delete tinyINTEGER NOT NULL,
date_created timestamp NOT NULL DEFAULT current_timestamp(),
date_updated timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
about text NOT NULL,
details mediumtext NOT NULL,
banner TEXT DEFAULT NULL,
PRIMARY KEY (id)
)`,
students: `CREATE TABLE IF NOT EXISTS students (
    id INTEGER NOT NULL,
    schoolid INTEGER NOT NULL,
    admission_no TEXT NOT NULL,
    admission_nox TEXT NOT NULL,
    oldadmission_no TEXT DEFAULT NULL,
    surname TEXT NOT NULL,
    firstname TEXT NOT NULL,
    middlename TEXT NOT NULL,
    gender TEXT NOT NULL,
    dob date NOT NULL,
    doa date NOT NULL,
    soo TEXT NOT NULL,
    religion TEXT NOT NULL,
    lga TEXT NOT NULL,
    nationality TEXT NOT NULL,
    cclass TEXT NOT NULL,
    is_active tinyINTEGER NOT NULL DEFAULT 0,
    is_delete tinyINTEGER NOT NULL DEFAULT 0,
    date_created timestamp NOT NULL DEFAULT current_timestamp(),
    date_updated timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
    photo TEXT NOT NULL,
    photo1 TEXT NOT NULL,
    photo2 TEXT NOT NULL,
    photo3 TEXT NOT NULL,
    house TEXT NOT NULL,
    place TEXT NOT NULL,
    admit TEXT NOT NULL,
    parentid INTEGER NOT NULL DEFAULT 0,
    g1_name TEXT NOT NULL,
    g1_address text NOT NULL,
    g1_rel TEXT NOT NULL,
    g1_phone1 TEXT NOT NULL,
    g1_phone2 TEXT NOT NULL,
    g1_email TEXT NOT NULL,
    g2_name TEXT NOT NULL,
    g2_address text NOT NULL,
    g2_rel TEXT NOT NULL,
    g2_phone1 TEXT NOT NULL,
    g2_phone2 TEXT NOT NULL,
    g2_email TEXT NOT NULL,
    g1_place TEXT NOT NULL,
    g2_place TEXT NOT NULL,
    is_email_confirmed tinyINTEGER NOT NULL DEFAULT 0
    )`,
subjects :  `CREATE TABLE IF NOT EXISTS subjects (
    id INTEGER NOT NULL ,
    schoolid INTEGER NOT NULL,
    typeid INTEGER NOT NULL,
    departmentid INTEGER NOT NULL,
    unitid INTEGER NOT NULL,
    name TEXT NOT NULL,
    abbrv TEXT NOT NULL,
    subunit INTEGER NOT NULL DEFAULT 0,
    weight float NOT NULL DEFAULT 1,
    is_active tinyINTEGER NOT NULL DEFAULT 0,
    is_delete tinyINTEGER NOT NULL DEFAULT 0,
    date_created timestamp NOT NULL DEFAULT current_timestamp(),
    date_updated timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
    PRIMARY KEY (id)
    )`,
 terms : `CREATE TABLE IF NOT EXISTS terms (
    id INTEGER NOT NULL ,
    sessionid INTEGER NOT NULL,
    name TEXT NOT NULL,
    started date NOT NULL,
    ended date NOT NULL,
    is_active tinyINTEGER NOT NULL DEFAULT 0,
    is_delete tinyINTEGER NOT NULL DEFAULT 0,
    date_created timestamp NOT NULL DEFAULT current_timestamp(),
    date_updated timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
    PRIMARY KEY (id)
    )`,
 sessions : `CREATE TABLE IF NOT EXISTS sessions (
    id INTEGER NOT NULL,
    schoolid INTEGER NOT NULL,
    name TEXT NOT NULL,
    started date NOT NULL,
    ended date NOT NULL,
    is_active tinyINTEGER NOT NULL DEFAULT 0,
    is_delete tinyINTEGER NOT NULL DEFAULT 0,
    date_created timestamp NOT NULL DEFAULT current_timestamp(),
    date_updated timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()
    )`
}